// <auto-generated />
using System;
using FutureValue.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FutureValue.Persistence.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20210702071756_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FutureValue.Domain.ExecutionDetails", b =>
                {
                    b.Property<int>("ExecutionDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("FutureValue")
                        .HasColumnType("Float");

                    b.Property<int>("FutureValueId")
                        .HasColumnType("int");

                    b.Property<int?>("FutureValuesId")
                        .HasColumnType("int");

                    b.Property<double>("InterestRate")
                        .HasColumnType("float");

                    b.Property<double>("Value")
                        .HasColumnType("Float");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("ExecutionDetailsId");

                    b.HasIndex("FutureValuesId");

                    b.ToTable("ExecutionDetails");
                });

            modelBuilder.Entity("FutureValue.Domain.FutureValues", b =>
                {
                    b.Property<int>("FutureValuesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ExecutionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DateTime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("IncrementalRate")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<int>("LowerBoundInterest")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<int>("MaturityYears")
                        .HasColumnType("int");

                    b.Property<double>("PresentValue")
                        .HasColumnType("Float");

                    b.Property<int>("UpperBoundInterest")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.HasKey("FutureValuesId");

                    b.ToTable("FutureValues");
                });

            modelBuilder.Entity("FutureValue.Domain.ExecutionDetails", b =>
                {
                    b.HasOne("FutureValue.Domain.FutureValues", "FutureValues")
                        .WithMany()
                        .HasForeignKey("FutureValuesId");

                    b.Navigation("FutureValues");
                });
#pragma warning restore 612, 618
        }
    }
}
